Fix failing tests due to different return codes
Fixes:
======================================================================
FAIL: test_invalid_key (tests.test_forecastio.EndToEnd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hassdev/python-forecast.io/tests/test_forecastio.py", line 47, in test_invalid_key
    self.assertEqual(str(e), '403 Client Error: Forbidden')
AssertionError: '400 Client Error: Bad Request for url: http[75 chars]auto' != '403 Client Error: Forbidden'
- 400 Client Error: Bad Request for url: https://api.darksky.net/forecast/not%20a%20real%20key/52.370235,4.903549?units=auto
+ 403 Client Error: Forbidden

-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.darksky.net
requests.packages.urllib3.connectionpool: DEBUG: "GET /forecast/not%20a%20real%20key/52.370235,4.903549?units=auto HTTP/1.1" 400 181
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_invalid_param (tests.test_forecastio.EndToEnd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hassdev/python-forecast.io/tests/test_forecastio.py", line 59, in test_invalid_param
    self.assertEqual(str(e), '400 Client Error: Bad Request')
AssertionError: '400 [20 chars]quest for url: https://api.darksky.net/forecas[23 chars]auto' != '400 [20 chars]quest'
- 400 Client Error: Bad Request for url: https://api.darksky.net/forecast/None/,4.903549?units=auto
+ 400 Client Error: Bad Request

-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.darksky.net
requests.packages.urllib3.connectionpool: DEBUG: "GET /forecast/None/,4.903549?units=auto HTTP/1.1" 400 181
--------------------- >> end captured logging << ---------------------